"""new fields in user model: about_me and last_seen

Revision ID: 35be88af94d0
Revises: 5890cb48f5b9
Create Date: 2018-12-13 07:01:13.030023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35be88af94d0'
down_revision = '5890cb48f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
