"""empty message

Revision ID: dcda8c717b5b
Revises: d3fcd9291abb
Create Date: 2019-01-08 04:11:32.593346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcda8c717b5b'
down_revision = 'd3fcd9291abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory', sa.Column('memorized', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_memory_memorized'), 'memory', ['memorized'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_memorized'), table_name='memory')
    op.drop_column('memory', 'memorized')
    # ### end Alembic commands ###
