"""empty message

Revision ID: fce96335805d
Revises: 3d3198f1b12f
Create Date: 2019-01-04 04:16:40.507665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce96335805d'
down_revision = '3d3198f1b12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tag',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_index('ix_tag_tag', table_name='tag')
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.create_index('ix_tag_tag', 'tag', ['tag'], unique=False)
    op.alter_column('tag', 'tag',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
